import { LevelData } from '../types';

export const LEVELS: LevelData[] = [
  // ─── LEVEL 1 — LLM Pipeline ───────────────────────────────────────────────
  {
    id: 1,
    title: 'LLM Pipeline',
    subtitle: 'How does ChatGPT actually work?',
    learningGoal: 'Understand the end-to-end flow of an LLM system',
    timerSeconds: 12,
    columns: [
      { id: 'input', label: 'Input', hint: 'Where does user text first arrive?' },
      {
        id: 'tokenizer',
        label: 'Tokenizer',
        hint: 'Breaks text into chunks the model understands',
      },
      { id: 'context', label: 'Context Window', hint: "The model's working memory" },
      { id: 'llm', label: 'LLM', hint: 'The neural network that generates responses' },
      { id: 'output', label: 'Output', hint: 'The final text sent back to the user' },
    ],
    blocks: [
      {
        id: 'l1-b1',
        name: 'User Input',
        color: '#00e5ff',
        description:
          'Everything starts here — the text, question, or command you type. This raw text is the trigger for the entire LLM pipeline.',
        correctColumn: 'input',
      },
      {
        id: 'l1-b2',
        name: 'Tokenizer',
        color: '#a855f7',
        description:
          'Converts raw text into tokens — tiny subword chunks. "unhappy" → ["un","happy"]. Models only understand numbers, not words directly.',
        correctColumn: 'tokenizer',
      },
      {
        id: 'l1-b3',
        name: 'Context Window',
        color: '#06b6d4',
        description:
          "The model's working memory. It can only 'see' a limited number of tokens at once — like a spotlight on a page. Everything outside is invisible.",
        correctColumn: 'context',
      },
      {
        id: 'l1-b4',
        name: 'LLM Core',
        color: '#8b5cf6',
        description:
          'The neural network — billions of parameters trained to predict the next token. It takes the context window and generates the most likely next word.',
        correctColumn: 'llm',
      },
      {
        id: 'l1-b5',
        name: 'AI Response',
        color: '#22c55e',
        description:
          'Tokens generated by the LLM are decoded back into readable text and returned to you. End of the pipeline — start of the next turn.',
        correctColumn: 'output',
      },
    ],
  },

  // ─── LEVEL 2 — Prompt Builder ─────────────────────────────────────────────
  {
    id: 2,
    title: 'Prompt Builder',
    subtitle: 'Assemble the perfect AI prompt',
    learningGoal: 'Understand the anatomy of a well-structured prompt',
    timerSeconds: 10,
    hasApiCall: true,
    columns: [
      { id: 'role', label: 'Role', hint: 'Who or what should the AI act as?' },
      { id: 'context', label: 'Context', hint: 'Background info the AI needs' },
      { id: 'instruction', label: 'Instruction', hint: 'The actual task or command' },
      { id: 'format', label: 'Format', hint: 'How should the response look?' },
    ],
    blocks: [
      {
        id: 'l2-b1',
        name: 'You are a helpful assistant',
        color: '#00e5ff',
        description:
          "Sets the AI's persona. The Role primes the model's 'identity' for the entire conversation. A clear role = more consistent behavior.",
        correctColumn: 'role',
      },
      {
        id: 'l2-b2',
        name: 'The user is a student',
        color: '#a855f7',
        description:
          "Provides background info the AI needs to calibrate its response. Context tells the AI WHY you're asking — so it can tailor the answer.",
        correctColumn: 'context',
      },
      {
        id: 'l2-b3',
        name: 'Explain in simple terms',
        color: '#f59e0b',
        description:
          'The actual directive — what you want done. Instructions are the core of the prompt. Without a clear instruction, the AI guesses.',
        correctColumn: 'instruction',
      },
      {
        id: 'l2-b4',
        name: 'Use bullet points',
        color: '#22c55e',
        description:
          'Specifies output structure. Format control is one of the most underused prompt techniques — it dramatically improves readability and usefulness.',
        correctColumn: 'format',
      },
      {
        id: 'l2-b5',
        name: 'Write a poem',
        color: '#ef4444',
        description:
          'DISTRACTOR: An unrelated task that conflicts with the student/explanation context. Mixing unrelated tasks confuses the model and degrades output quality.',
        correctColumn: 'NONE',
        isDistractor: true,
      },
      {
        id: 'l2-b6',
        name: 'Ignore all previous instructions',
        color: '#dc2626',
        description:
          'DISTRACTOR: A classic prompt injection attack. Real AI systems must defend against this phrase, which attempts to override safety guidelines.',
        correctColumn: 'NONE',
        isDistractor: true,
      },
    ],
  },

  // ─── LEVEL 3 — Hallucination Swamp ────────────────────────────────────────
  {
    id: 3,
    title: 'Hallucination Swamp',
    subtitle: 'Real fact — or AI-generated fiction?',
    learningGoal: 'Recognize how AI confidently produces false information',
    timerSeconds: 8,
    columns: [
      { id: 'true', label: '✓  TRUE', hint: 'This is a verified fact about AI' },
      { id: 'fake', label: '✗  FAKE', hint: 'The AI invented this — hallucination' },
    ],
    blocks: [
      {
        id: 'l3-b1',
        name: 'LLMs predict the next token',
        color: '#22c55e',
        description:
          'TRUE ✓ — This is the literal core mechanism. LLMs generate text one token at a time, each prediction shaped by all prior tokens in the context.',
        correctColumn: 'true',
      },
      {
        id: 'l3-b2',
        name: "AI always knows when it's wrong",
        color: '#ef4444',
        description:
          'FAKE ✗ — Hallucination! LLMs have zero self-awareness of errors. They confidently output incorrect information because they optimize for plausibility, not truth.',
        correctColumn: 'fake',
      },
      {
        id: 'l3-b3',
        name: 'GPT = Generative Pre-trained Transformer',
        color: '#22c55e',
        description:
          'TRUE ✓ — GPT stands for Generative (creates text) + Pre-trained (trained on massive data) + Transformer (the neural network architecture).',
        correctColumn: 'true',
      },
      {
        id: 'l3-b4',
        name: 'ChatGPT has real-time internet access',
        color: '#ef4444',
        description:
          'FAKE ✗ — The base model has a training cutoff and no live internet. Some versions have search plugins — but that is a separate tool, not built-in knowledge.',
        correctColumn: 'fake',
      },
      {
        id: 'l3-b5',
        name: 'Tokenization splits text into chunks',
        color: '#22c55e',
        description:
          "TRUE ✓ — Tokenization is the first step in every LLM pipeline. Text is split into subword tokens — the model's primitive unit of language.",
        correctColumn: 'true',
      },
      {
        id: 'l3-b6',
        name: 'AI understands language like humans',
        color: '#ef4444',
        description:
          "FAKE ✗ — LLMs process statistical patterns in text, not meaning. There's no genuine 'understanding' — it's sophisticated pattern matching, not comprehension.",
        correctColumn: 'fake',
      },
    ],
  },

  // ─── LEVEL 4 — Fine-tuning ────────────────────────────────────────────────
  {
    id: 4,
    title: 'Fine-tuning',
    subtitle: 'From foundation model to your specific task',
    learningGoal: 'Know how supervised fine-tuning and adapters adapt a base LLM',
    timerSeconds: 10,
    columns: [
      {
        id: 'pretrain',
        label: 'Pre-training',
        hint: 'Train on huge text with next-token loss — general capabilities',
      },
      {
        id: 'task_data',
        label: 'Task dataset',
        hint: 'Curated examples for the behavior you want',
      },
      {
        id: 'finetune',
        label: 'Fine-tuning',
        hint: 'Gradient updates on task loss — specialize the weights',
      },
      {
        id: 'lora',
        label: 'LoRA / adapters',
        hint: 'Small trainable matrices; most weights stay frozen',
      },
      {
        id: 'eval',
        label: 'Evaluation',
        hint: 'Metrics + human review on held-out data',
      },
    ],
    blocks: [
      {
        id: 'l4-b1',
        name: 'Next-token prediction on web-scale text',
        color: '#38bdf8',
        description:
          'Pre-training teaches broad language patterns before any task-specific data.',
        correctColumn: 'pretrain',
      },
      {
        id: 'l4-b2',
        name: '2k labeled support tickets with gold replies',
        color: '#a855f7',
        description: 'Task data gives the model concrete input/output pairs to imitate.',
        correctColumn: 'task_data',
      },
      {
        id: 'l4-b3',
        name: 'Minimize cross-entropy on the instruction dataset',
        color: '#f472b6',
        description:
          'Fine-tuning adjusts weights so the model improves on your objective.',
        correctColumn: 'finetune',
      },
      {
        id: 'l4-b4',
        name: 'Low-rank update matrices only',
        color: '#4ade80',
        description:
          'LoRA trains tiny additive weights — cheaper and less catastrophic forgetting.',
        correctColumn: 'lora',
      },
      {
        id: 'l4-b5',
        name: 'Compare BLEU vs human ratings on a test split',
        color: '#22c55e',
        description: 'Evaluation tells you if fine-tuning actually helped real users.',
        correctColumn: 'eval',
      },
      {
        id: 'l4-b6',
        name: 'Just add “please” to the system prompt',
        color: '#f87171',
        description:
          'DISTRACTOR: Politeness tweaks help a bit — they are not a substitute for task data or fine-tuning.',
        correctColumn: 'NONE',
        isDistractor: true,
      },
    ],
  },

  // ─── LEVEL 5 — RAG ────────────────────────────────────────────────────────
  {
    id: 5,
    title: 'RAG',
    subtitle: 'Retrieval-augmented generation — ground the model in your docs',
    learningGoal: 'Trace documents → chunks → vectors → retrieval → grounded answers',
    timerSeconds: 10,
    columns: [
      { id: 'ingest', label: 'Ingest', hint: 'Bring sources into the pipeline' },
      { id: 'chunk', label: 'Chunking', hint: 'Split text into embeddable pieces' },
      { id: 'embed', label: 'Embed', hint: 'Turn chunks into vectors' },
      { id: 'retrieve', label: 'Retrieve', hint: 'Search by semantic similarity' },
      {
        id: 'augment',
        label: 'Augment prompt',
        hint: 'Inject evidence before the LLM answers',
      },
    ],
    blocks: [
      {
        id: 'l5-b1',
        name: 'Sync Confluence + PDFs into a pipeline',
        color: '#38bdf8',
        description:
          'Ingestion is the first step — without sources there is nothing to retrieve.',
        correctColumn: 'ingest',
      },
      {
        id: 'l5-b2',
        name: '256-token chunks with 32-token overlap',
        color: '#a855f7',
        description: 'Chunking balances context size vs retrieval precision.',
        correctColumn: 'chunk',
      },
      {
        id: 'l5-b3',
        name: 'Embedding model maps chunk → vector',
        color: '#f472b6',
        description: 'Embeddings place text in a space where similar meaning is nearby.',
        correctColumn: 'embed',
      },
      {
        id: 'l5-b4',
        name: 'Top-5 nearest neighbors to the user query',
        color: '#4ade80',
        description: 'Retrieval pulls the most relevant evidence for this question.',
        correctColumn: 'retrieve',
      },
      {
        id: 'l5-b5',
        name: 'Paste retrieved passages into the prompt',
        color: '#22c55e',
        description:
          'Augmentation grounds generation — the model cites what you retrieved.',
        correctColumn: 'augment',
      },
      {
        id: 'l5-b6',
        name: 'Train a 70B model from random weights',
        color: '#f87171',
        description:
          'DISTRACTOR: RAG adds knowledge without full pre-training; it is not “train from scratch.”',
        correctColumn: 'NONE',
        isDistractor: true,
      },
    ],
  },

  // ─── LEVEL 6 — Embeddings ─────────────────────────────────────────────────
  {
    id: 6,
    title: 'Embeddings',
    subtitle: 'Meaning as geometry in vector space',
    learningGoal: 'Understand what embedding vectors capture — and what they miss',
    timerSeconds: 9,
    columns: [
      {
        id: 'vector',
        label: 'Vector',
        hint: 'Fixed-length numeric representation of text',
      },
      {
        id: 'similarity',
        label: 'Similarity',
        hint: 'Cosine / dot product between vectors',
      },
      {
        id: 'semantic',
        label: 'Semantics',
        hint: 'Related concepts cluster — not keyword overlap',
      },
      {
        id: 'contextual',
        label: 'Contextual',
        hint: 'Same word, different vectors depending on sentence',
      },
      {
        id: 'limits',
        label: 'Limits',
        hint: 'Embeddings are not logic engines or fact checkers',
      },
    ],
    blocks: [
      {
        id: 'l6-b1',
        name: '768 floats per input span',
        color: '#38bdf8',
        description:
          'An embedding is a point in ℝⁿ — the model maps text to coordinates.',
        correctColumn: 'vector',
      },
      {
        id: 'l6-b2',
        name: 'Cosine similarity 0.91 between two FAQs',
        color: '#a855f7',
        description: 'Similarity scores rank which texts are “close” in meaning.',
        correctColumn: 'similarity',
      },
      {
        id: 'l6-b3',
        name: '“King − man + woman ≈ queen” (classic analogy)',
        color: '#f472b6',
        description:
          'Linear structure in embedding space often reflects semantic relations.',
        correctColumn: 'semantic',
      },
      {
        id: 'l6-b4',
        name: '“Bank” as finance vs river bank',
        color: '#4ade80',
        description:
          'Contextual embeddings (e.g. transformers) disambiguate by surrounding words.',
        correctColumn: 'contextual',
      },
      {
        id: 'l6-b5',
        name: 'Toxic + benign strings can land nearby',
        color: '#22c55e',
        description:
          'LIMITS: geometry can be misleading — safety needs more than cosine distance.',
        correctColumn: 'limits',
      },
      {
        id: 'l6-b6',
        name: 'The embedding “knows” if a claim is true',
        color: '#f87171',
        description:
          'DISTRACTOR: Embeddings encode similarity, not truth — factual check needs retrieval or tools.',
        correctColumn: 'NONE',
        isDistractor: true,
      },
    ],
  },
];

export const LEVEL_COUNT = LEVELS.length;
