import { LevelData } from '../types';

export const LEVELS: LevelData[] = [
  // ─── LEVEL 1 — LLM Pipeline ───────────────────────────────────────────────
  {
    id: 1,
    title: 'LLM Pipeline',
    subtitle: 'How does ChatGPT actually work?',
    learningGoal: 'Understand the end-to-end flow of an LLM system',
    timerSeconds: 12,
    columns: [
      { id: 'input',     label: 'Input',          hint: 'Where does user text first arrive?' },
      { id: 'tokenizer', label: 'Tokenizer',       hint: 'Breaks text into chunks the model understands' },
      { id: 'context',   label: 'Context Window',  hint: "The model's working memory" },
      { id: 'llm',       label: 'LLM',             hint: 'The neural network that generates responses' },
      { id: 'output',    label: 'Output',           hint: 'The final text sent back to the user' },
    ],
    blocks: [
      {
        id: 'l1-b1',
        name: 'User Input',
        color: '#00e5ff',
        description:
          'Everything starts here — the text, question, or command you type. This raw text is the trigger for the entire LLM pipeline.',
        correctColumn: 'input',
      },
      {
        id: 'l1-b2',
        name: 'Tokenizer',
        color: '#a855f7',
        description:
          'Converts raw text into tokens — tiny subword chunks. "unhappy" → ["un","happy"]. Models only understand numbers, not words directly.',
        correctColumn: 'tokenizer',
      },
      {
        id: 'l1-b3',
        name: 'Context Window',
        color: '#06b6d4',
        description:
          "The model's working memory. It can only 'see' a limited number of tokens at once — like a spotlight on a page. Everything outside is invisible.",
        correctColumn: 'context',
      },
      {
        id: 'l1-b4',
        name: 'LLM Core',
        color: '#8b5cf6',
        description:
          'The neural network — billions of parameters trained to predict the next token. It takes the context window and generates the most likely next word.',
        correctColumn: 'llm',
      },
      {
        id: 'l1-b5',
        name: 'AI Response',
        color: '#22c55e',
        description:
          'Tokens generated by the LLM are decoded back into readable text and returned to you. End of the pipeline — start of the next turn.',
        correctColumn: 'output',
      },
    ],
  },

  // ─── LEVEL 2 — Prompt Builder ─────────────────────────────────────────────
  {
    id: 2,
    title: 'Prompt Builder',
    subtitle: 'Assemble the perfect AI prompt',
    learningGoal: 'Understand the anatomy of a well-structured prompt',
    timerSeconds: 10,
    hasApiCall: true,
    columns: [
      { id: 'role',        label: 'Role',        hint: 'Who or what should the AI act as?' },
      { id: 'context',     label: 'Context',     hint: 'Background info the AI needs' },
      { id: 'instruction', label: 'Instruction', hint: 'The actual task or command' },
      { id: 'format',      label: 'Format',      hint: 'How should the response look?' },
    ],
    blocks: [
      {
        id: 'l2-b1',
        name: 'You are a helpful assistant',
        color: '#00e5ff',
        description:
          "Sets the AI's persona. The Role primes the model's 'identity' for the entire conversation. A clear role = more consistent behavior.",
        correctColumn: 'role',
      },
      {
        id: 'l2-b2',
        name: 'The user is a student',
        color: '#a855f7',
        description:
          "Provides background info the AI needs to calibrate its response. Context tells the AI WHY you're asking — so it can tailor the answer.",
        correctColumn: 'context',
      },
      {
        id: 'l2-b3',
        name: 'Explain in simple terms',
        color: '#f59e0b',
        description:
          "The actual directive — what you want done. Instructions are the core of the prompt. Without a clear instruction, the AI guesses.",
        correctColumn: 'instruction',
      },
      {
        id: 'l2-b4',
        name: 'Use bullet points',
        color: '#22c55e',
        description:
          'Specifies output structure. Format control is one of the most underused prompt techniques — it dramatically improves readability and usefulness.',
        correctColumn: 'format',
      },
      {
        id: 'l2-b5',
        name: 'Write a poem',
        color: '#ef4444',
        description:
          'DISTRACTOR: An unrelated task that conflicts with the student/explanation context. Mixing unrelated tasks confuses the model and degrades output quality.',
        correctColumn: 'NONE',
        isDistractor: true,
      },
      {
        id: 'l2-b6',
        name: 'Ignore all previous instructions',
        color: '#dc2626',
        description:
          'DISTRACTOR: A classic prompt injection attack. Real AI systems must defend against this phrase, which attempts to override safety guidelines.',
        correctColumn: 'NONE',
        isDistractor: true,
      },
    ],
  },

  // ─── LEVEL 3 — Hallucination Swamp ────────────────────────────────────────
  {
    id: 3,
    title: 'Hallucination Swamp',
    subtitle: 'Real fact — or AI-generated fiction?',
    learningGoal: 'Recognize how AI confidently produces false information',
    timerSeconds: 8,
    columns: [
      { id: 'true', label: '✓  TRUE', hint: 'This is a verified fact about AI' },
      { id: 'fake', label: '✗  FAKE', hint: 'The AI invented this — hallucination' },
    ],
    blocks: [
      {
        id: 'l3-b1',
        name: 'LLMs predict the next token',
        color: '#22c55e',
        description:
          'TRUE ✓ — This is the literal core mechanism. LLMs generate text one token at a time, each prediction shaped by all prior tokens in the context.',
        correctColumn: 'true',
      },
      {
        id: 'l3-b2',
        name: "AI always knows when it's wrong",
        color: '#ef4444',
        description:
          'FAKE ✗ — Hallucination! LLMs have zero self-awareness of errors. They confidently output incorrect information because they optimize for plausibility, not truth.',
        correctColumn: 'fake',
      },
      {
        id: 'l3-b3',
        name: 'GPT = Generative Pre-trained Transformer',
        color: '#22c55e',
        description:
          'TRUE ✓ — GPT stands for Generative (creates text) + Pre-trained (trained on massive data) + Transformer (the neural network architecture).',
        correctColumn: 'true',
      },
      {
        id: 'l3-b4',
        name: 'ChatGPT has real-time internet access',
        color: '#ef4444',
        description:
          'FAKE ✗ — The base model has a training cutoff and no live internet. Some versions have search plugins — but that is a separate tool, not built-in knowledge.',
        correctColumn: 'fake',
      },
      {
        id: 'l3-b5',
        name: 'Tokenization splits text into chunks',
        color: '#22c55e',
        description:
          "TRUE ✓ — Tokenization is the first step in every LLM pipeline. Text is split into subword tokens — the model's primitive unit of language.",
        correctColumn: 'true',
      },
      {
        id: 'l3-b6',
        name: 'AI understands language like humans',
        color: '#ef4444',
        description:
          "FAKE ✗ — LLMs process statistical patterns in text, not meaning. There's no genuine 'understanding' — it's sophisticated pattern matching, not comprehension.",
        correctColumn: 'fake',
      },
    ],
  },
];
